repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^test/cases/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy

- repo: local
  hooks:

  - # https://github.com/nedbat/cog/issues/21#issuecomment-1919626992
    id: cog
    name: cog (regenerate files)
    language: python
    additional_dependencies:
    - cogapp
    entry: bash -c 'git grep -lzF "[[[""cog" | xargs -0 cog "$@"'
    args:
    - '' # (first argument swallowed by bash)
    - -c # Checksum the output to protect it against accidental change.
    - -r # Replace the input file with the output.
    - -P # Use print() instead of cog.outl() for code output.
    - -p # Prepend the generator source with PROLOGUE:
    - "import subprocess as sp, os"
    pass_filenames: false
    always_run: true

  - id: tests
    name: tests
    language: system
    entry: python -m unittest
    pass_filenames: false
    files: '\.py$'
